sudo : required
language: java

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
 - oraclejdk8

env:
 - JAVA_6_HOME=/usr/lib/jvm/java-6-openjdk-amd64
   JAVA_7_HOME=/usr/lib/jvm/java-7-openjdk-amd64
   JAVA_8_HOME=/usr/lib/jvm/java-8-oracle
   JAVA_9_HOME=/usr/lib/jvm/java-9-oracle
   GH_USER= RoySRose
   GH_REPO= pinpoint
   secure= ZBrxvfeGzS5jiUsUJ16QBu1PdO5WOf1seGQXdDPzOQBtR9KhoJoRX0PNq+wiSsg/9quJXGQ4+zTLUnpZB+v3jgcnSG8Dhvc+Vu1soNHjFcs+sgmL18nnKOe/sPjucBA5ViNxRqYH1mVyIwwqYJXdy8I6BbsbgM7JT6JspD4Q8qr7deHQ2QQCB7h1OqnzjBfwpTxYNw2sbbYVCBpSsgUxGJkOJRqJU84pAJ+MMSke3lVG46ptlJlfEP5930Z+n4oEJGIx0Yo7L1AIovJyerneQqxgSIAYm7A8os6wU38BcgxA5BP5qGins0cZ6TCSETBnyuQbgP3Lm6Kb2Uudezi01/aegd+x4Hl2n0S37pgKk32a3WLqLJMwZWEtGRiF6HNdwxBNuNsA1qYG5aF2utiCPsgVcwJJrMKXa/lZuvwMmWKogc6GNrhOCA8B8ck1VafYhbhJkWaERYXNMapvMbUWqnklygE/dbQxpgzbxwm9UWuFuqBhbn6P5jB6vracbXHmotTvtnB1kbmzH7FfqQ6WQi1nRR3GvAq0U7l+26FozprjsdmDAWV6I8/LTpoI9LsjjKV+E6sm+CHqKnIh/594H/T/gkbBpggpdqgO6i2yfrsHuvjsybFWFX6NZ71+w45LD0oP5adQSPBXGICOcIID83Bor3Vsr47rE7zL6BH0t0M=

install:
 - set -o pipefail
 - ls -al $JAVA_6_HOME
 - ls -al $JAVA_7_HOME
 - ls -al $JAVA_8_HOME
 - ls -al $JAVA_9_HOME
 - $JAVA_6_HOME/bin/java -version
 - $JAVA_7_HOME/bin/java -version
 - $JAVA_8_HOME/bin/java -version
 - $JAVA_9_HOME/bin/java -version
 - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V | grep -Fv '[copy'

script:
 - jdk_switcher use oraclejdk8
 - ./mvnw clover:setup test -Ptest clover:aggregate clover:clover -e | grep -Fv 'DEBUG' | grep -Fv '[copy'

after_success:
 - bash <(curl -s https://codecov.io/bash)
 - bash ./scripts/deployGitPage.sh

dist:
 - trusty