language: java

cache:
  directories:
    - $HOME/.m2
    - web/src/main/angular/node_modules
    - node_install

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
 - oraclejdk8

env:
  global:
   - secure: FpEVxxTvDeACV2FTjXPOlO0ua6Jq7D2yOuYPjY0iDh4LlPgGeLIei797iC6pFKdehRaHu0s3K3k09x+ffAm0LmQ6Fc/iENg17TkxJ/fDfyl0CHVU5bGA1L7Pp8pOBC0sVISZ3JQgCMRd/CxvV9rgzEdZkm8WeGipi0Jkv6Eomh8=
   - JAVA_6_HOME=/usr/lib/jvm/java-6-openjdk-amd64
     JAVA_7_HOME=/usr/lib/jvm/java-7-openjdk-amd64
     JAVA_8_HOME=/usr/lib/jvm/java-8-oracle
     JAVA_9_HOME=/usr/lib/jvm/java-9-oracle

install:
 - set -o pipefail
 - ls -al $JAVA_6_HOME
 - ls -al $JAVA_7_HOME
 - ls -al $JAVA_8_HOME
 - ls -al $JAVA_9_HOME
 - $JAVA_6_HOME/bin/java -version
 - $JAVA_7_HOME/bin/java -version
 - $JAVA_8_HOME/bin/java -version
 - $JAVA_9_HOME/bin/java -version
 - ./mvnw install -DskipTests=true -Plocal -Dmaven.javadoc.skip=true -B -V | grep -Fv '[copy'

script:
 - jdk_switcher use oraclejdk8
 - ./mvnw clover:setup test -Plocal,test clover:aggregate clover:clover -e | grep -Fv 'DEBUG' | grep -Fv '[copy'

after_success:
 - bash <(curl -s https://codecov.io/bash)
 - bash ./doc/scripts/deployGitPage.sh

dist:
 - trusty
