/**
 * Autogenerated by Thrift Compiler (0.10.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.navercorp.pinpoint.api.util;

/**
 * @author Roy Kim
 */

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TraceConstants {

    public static final byte TRACE_V1 = (byte) 0;

    public static final byte TRACE_V2 = (byte) 1;

}
